### ISSUE TITLE
Casings only have two light levels

### ISSUE THREAD

**Issue by knishle** [liquidplasma/InsurgencyWeapons#2]
In complete darkness bullet casings disappear, but when exposed to any amount of light they are always completely visible

**Comment by liquidplasma** [comment]
One of the reasons I don't like using gore for this kind of stuff. I could go back to projectile casings tho

**Comment by knishle** [comment]
> One of the reasons I don't like using gore for this kind of stuff. I could go back to projectile casings tho

Gore works well with Terraria Overhaul though, since it persists & can be swept around. If anything I'd say just don't bother, it's not really a big issue or that annoying

**Comment by liquidplasma** [comment]
fixed in 
e51fd6b
