### ISSUE TITLE
Rounds in magazine disappear upon reload

### ISSUE THREAD

**Issue by knishle** [liquidplasma/InsurgencyWeapons#3]
Difficult to reproduce, and different behaviors on different weapons.

Upon reloading the world, guns stored in a chest were not affected

Upon reloading the entire game, the M249 LMG had it's full 200rnd magazine emptied, and the G3 lost a single round in the chamber. Other guns also seem to lose ammo, Maybe an issue with some commando weapons. 

I've also noticed guns in the inventory sometimes lost their magazine capacity as well, but not yet reproduced

**Comment by knishle** [comment]
Some further testing, and the enfield has its magazine completely emptied while in the inventory upon reloading the game

(Weapon in chest behavior)
The G3 previously mentioned to have lost a chambered round upon world reload is now completely empty upon another world reload. Two other weapons, the coach gun and the M40A1 also empty their mags upon world reload. The only unaffected firearm currently is the Mossberg, so no clear correlation with any gun class.

**Comment by liquidplasma** [comment]
I'm aware of the magazine loading issue, as the way I did it was quite simple. Magazine filling is done once when you enter the world, exiting and re-entering make you lose the rounds the magazine. I'll have to come up with some other way of keeping track

**Comment by liquidplasma** [comment]
Changed to saving using tagcompounds in a525864
