### ISSUE TITLE
(Minor) Misc strange behaviors when reloading

### ISSUE THREAD

**Issue by knishle** [liquidplasma/InsurgencyWeapons#4]
The .38 revolver is able to play an animation for opening and closing the cylinder when reloading with a full magazine. It's pretty cool, but maybe not intended.

The .303 enfield ejects a single round and replaces it upon reloading with a full magazine. Stimming behaviour?

**Comment by knishle** [comment]
Meant the .357 not 38. The python.

**Comment by liquidplasma** [comment]
Should be fixed with a525864
