### ISSUE TITLE
Request: Merge simplified Chinese localization files

### ISSUE THREAD

**Issue by jd-ouswhsnnn** [liquidplasma/InsurgencyWeapons#5]
Since I am not familiar with how to use pull requests, I have submitted an issue instead
[zh-Hans_Mods.InsurgencyWeapons.zip](https://github.com/user-attachments/files/17364209/zh-Hans_Mods.InsurgencyWeapons.zip)
Mod version v0.9.3

**Comment by liquidplasma** [comment]
I'll take a look

**Comment by liquidplasma** [comment]
Added in 14ab8acbaa03c6d072a825747a55c4f0f4cef363
