### ISSUE TITLE
Chinese localization v0.9.6 update

### ISSUE THREAD

**Issue by jd-ouswhsnnn** [liquidplasma/InsurgencyWeapons#6]
[zh-Hans_Mods.InsurgencyWeapons.zip](https://github.com/user-attachments/files/17749959/zh-Hans_Mods.InsurgencyWeapons.zip)

**Comment by liquidplasma** [comment]
Hey, you do not need to translate any entry in _Projectiles_, the player will never see them

**Comment by liquidplasma** [comment]
Added in 
2ad6e74

**Comment by liquidplasma** [comment]
There is no need to place what ever gun uses the ammo anymore, I've made system that does that
